"""
C1-C2 Level English Vocabulary
Pre-loaded so the bot works immediately
"""

VOCABULARY = [
    # Day 1
    {"word": "ubiquitous", "definition": "present, appearing, or found everywhere", "example": "Smartphones have become ubiquitous in modern society."},
    {"word": "ephemeral", "definition": "lasting for a very short time", "example": "Fame on social media is often ephemeral."},
    {"word": "pragmatic", "definition": "dealing with things sensibly and realistically", "example": "We need a pragmatic approach to solve this problem."},
    {"word": "eloquent", "definition": "fluent or persuasive in speaking or writing", "example": "She gave an eloquent speech that moved everyone."},
    {"word": "meticulous", "definition": "showing great attention to detail", "example": "He was meticulous in his research."},
    {"word": "ambiguous", "definition": "open to more than one interpretation", "example": "The contract language was ambiguous."},
    {"word": "resilient", "definition": "able to recover quickly from difficulties", "example": "Children are remarkably resilient."},
    {"word": "contemplate", "definition": "look at thoughtfully; think about", "example": "She sat contemplating her next move."},
    {"word": "exacerbate", "definition": "make a problem worse", "example": "The drought exacerbated the food shortage."},
    {"word": "inevitable", "definition": "certain to happen; unavoidable", "example": "Change is inevitable in life."},
    {"word": "undermine", "definition": "weaken or damage gradually", "example": "His comments undermined her confidence."},
    {"word": "paradox", "definition": "a seemingly contradictory statement that may be true", "example": "It's a paradox that the busiest people often have the most time."},
    {"word": "profound", "definition": "very great or intense; deep", "example": "The book had a profound impact on me."},
    {"word": "albeit", "definition": "although; even though", "example": "He accepted the job, albeit with some reservations."},
    {"word": "nuance", "definition": "a subtle difference in meaning", "example": "She understood the nuances of the language."},
    
    # Day 2
    {"word": "intrinsic", "definition": "belonging naturally; essential", "example": "Curiosity is intrinsic to human nature."},
    {"word": "compelling", "definition": "evoking interest or attention; convincing", "example": "She made a compelling argument."},
    {"word": "scrutinize", "definition": "examine or inspect closely", "example": "The document was scrutinized for errors."},
    {"word": "mitigate", "definition": "make less severe or serious", "example": "We need to mitigate the risks."},
    {"word": "coherent", "definition": "logical and consistent", "example": "He struggled to form a coherent sentence."},
    {"word": "derivative", "definition": "not original; based on something else", "example": "The movie felt derivative of earlier films."},
    {"word": "arbitrary", "definition": "based on random choice rather than reason", "example": "The decision seemed arbitrary."},
    {"word": "tangible", "definition": "clear and definite; real", "example": "We need tangible results."},
    {"word": "complacent", "definition": "self-satisfied; uncritically content", "example": "Don't become complacent about your success."},
    {"word": "volatile", "definition": "liable to change rapidly; unstable", "example": "The stock market is volatile."},
    {"word": "substantiate", "definition": "provide evidence to support", "example": "Can you substantiate your claims?"},
    {"word": "unprecedented", "definition": "never done or known before", "example": "We're facing unprecedented challenges."},
    {"word": "pertinent", "definition": "relevant or applicable", "example": "That's a pertinent question."},
    {"word": "discrepancy", "definition": "a difference between things that should be the same", "example": "There's a discrepancy in the accounts."},
    {"word": "amalgamate", "definition": "combine or unite to form one", "example": "The two companies amalgamated."},
    
    # Day 3
    {"word": "juxtapose", "definition": "place side by side for comparison", "example": "The film juxtaposes wealth and poverty."},
    {"word": "convoluted", "definition": "extremely complex and difficult to follow", "example": "The plot was too convoluted."},
    {"word": "inundate", "definition": "overwhelm with things to deal with", "example": "We were inundated with requests."},
    {"word": "circumvent", "definition": "find a way around an obstacle", "example": "They tried to circumvent the rules."},
    {"word": "corroborate", "definition": "confirm or give support to", "example": "The witness corroborated his story."},
    {"word": "disseminate", "definition": "spread information widely", "example": "Social media helps disseminate news quickly."},
    {"word": "proliferate", "definition": "increase rapidly in number", "example": "Fake news has proliferated online."},
    {"word": "vindicate", "definition": "clear of blame; prove right", "example": "The evidence vindicated him completely."},
    {"word": "extraneous", "definition": "irrelevant or unrelated", "example": "Remove any extraneous details."},
    {"word": "rudimentary", "definition": "basic; not developed", "example": "He has only rudimentary knowledge."},
    {"word": "stringent", "definition": "strict, precise, and demanding", "example": "They have stringent quality controls."},
    {"word": "mundane", "definition": "lacking interest; ordinary", "example": "She was tired of mundane tasks."},
    {"word": "sporadic", "definition": "occurring at irregular intervals", "example": "There were sporadic outbursts of violence."},
    {"word": "tenuous", "definition": "very weak or slight", "example": "The connection seems tenuous."},
    {"word": "viable", "definition": "capable of working successfully", "example": "Is this a viable solution?"},
    
    # Day 4
    {"word": "acquiesce", "definition": "accept something reluctantly without protest", "example": "She acquiesced to their demands."},
    {"word": "belligerent", "definition": "hostile and aggressive", "example": "He became belligerent after drinking."},
    {"word": "clandestine", "definition": "kept secret; done secretly", "example": "They held clandestine meetings."},
    {"word": "denounce", "definition": "publicly declare to be wrong", "example": "They denounced the violence."},
    {"word": "embellish", "definition": "make more attractive; exaggerate", "example": "He tends to embellish his stories."},
    {"word": "fluctuate", "definition": "rise and fall irregularly", "example": "Prices fluctuate throughout the day."},
    {"word": "gratuitous", "definition": "uncalled for; unnecessary", "example": "The film had gratuitous violence."},
    {"word": "haphazard", "definition": "lacking organization or planning", "example": "The search was haphazard."},
    {"word": "imminent", "definition": "about to happen", "example": "A storm is imminent."},
    {"word": "judiciously", "definition": "with good judgment; wisely", "example": "Use your resources judiciously."},
    {"word": "kindle", "definition": "arouse or inspire an emotion", "example": "The speech kindled hope."},
    {"word": "lethargic", "definition": "lacking energy; sluggish", "example": "The heat made everyone lethargic."},
    {"word": "mollify", "definition": "calm someone's anger", "example": "Nothing could mollify her."},
    {"word": "nonchalant", "definition": "casually calm and relaxed", "example": "He seemed nonchalant about the results."},
    {"word": "ostentatious", "definition": "designed to impress; showy", "example": "The mansion was ostentatious."},
    
    # Day 5
    {"word": "palpable", "definition": "able to be touched or felt; obvious", "example": "The tension was palpable."},
    {"word": "quintessential", "definition": "representing the perfect example", "example": "She's the quintessential professional."},
    {"word": "repudiate", "definition": "refuse to accept; deny", "example": "He repudiated the accusations."},
    {"word": "succinct", "definition": "briefly and clearly expressed", "example": "Keep your answers succinct."},
    {"word": "tacit", "definition": "understood without being stated", "example": "They had a tacit agreement."},
    {"word": "unequivocal", "definition": "leaving no doubt; clear", "example": "Her answer was unequivocal."},
    {"word": "venerate", "definition": "regard with great respect", "example": "He is venerated as a hero."},
    {"word": "warrant", "definition": "justify or necessitate", "example": "The situation warrants investigation."},
    {"word": "zealous", "definition": "showing great enthusiasm", "example": "She was zealous in her efforts."},
    {"word": "ameliorate", "definition": "make something bad better", "example": "Steps were taken to ameliorate conditions."},
    {"word": "blatant", "definition": "done openly; obvious", "example": "It was a blatant lie."},
    {"word": "cryptic", "definition": "having hidden meaning; mysterious", "example": "She left a cryptic message."},
    {"word": "debunk", "definition": "expose falseness of an idea", "example": "Scientists debunked the myth."},
    {"word": "elicit", "definition": "draw out a response", "example": "The question elicited laughter."},
    {"word": "foster", "definition": "encourage the development of", "example": "We want to foster creativity."},
    
    # Day 6
    {"word": "gregarious", "definition": "fond of company; sociable", "example": "He's naturally gregarious."},
    {"word": "hypothetical", "definition": "imagined; not necessarily real", "example": "Let's consider a hypothetical situation."},
    {"word": "impeccable", "definition": "perfect; flawless", "example": "Her timing was impeccable."},
    {"word": "jeopardize", "definition": "put at risk", "example": "Don't jeopardize your career."},
    {"word": "lackadaisical", "definition": "lacking enthusiasm; lazy", "example": "His attitude was lackadaisical."},
    {"word": "magnanimous", "definition": "generous or forgiving", "example": "She was magnanimous in victory."},
    {"word": "negligible", "definition": "so small as to be meaningless", "example": "The difference is negligible."},
    {"word": "oblivious", "definition": "unaware of what's happening", "example": "He was oblivious to the danger."},
    {"word": "perpetuate", "definition": "make something continue indefinitely", "example": "We shouldn't perpetuate stereotypes."},
    {"word": "quintessence", "definition": "the perfect example of something", "example": "This dish is the quintessence of Italian cuisine."},
    {"word": "ramification", "definition": "consequence of an action", "example": "Consider the ramifications carefully."},
    {"word": "superfluous", "definition": "unnecessary; more than needed", "example": "Remove any superfluous words."},
    {"word": "transient", "definition": "lasting only a short time", "example": "Fame is often transient."},
    {"word": "usurp", "definition": "take power illegally or by force", "example": "He tried to usurp the throne."},
    {"word": "verbose", "definition": "using more words than needed", "example": "His writing style is too verbose."},
    
    # Day 7
    {"word": "wary", "definition": "feeling cautious about dangers", "example": "Be wary of strangers online."},
    {"word": "abhor", "definition": "regard with disgust and hatred", "example": "I abhor violence of any kind."},
    {"word": "benevolent", "definition": "well-meaning and kindly", "example": "A benevolent smile crossed her face."},
    {"word": "capricious", "definition": "given to sudden changes of mood", "example": "The weather here is capricious."},
    {"word": "delineate", "definition": "describe or portray precisely", "example": "The report delineates the options clearly."},
    {"word": "enigmatic", "definition": "difficult to interpret; mysterious", "example": "She gave an enigmatic smile."},
    {"word": "frivolous", "definition": "not having serious purpose", "example": "Don't waste money on frivolous things."},
    {"word": "germane", "definition": "relevant to a subject", "example": "That point isn't germane to our discussion."},
    {"word": "heinous", "definition": "utterly wicked or evil", "example": "It was a heinous crime."},
    {"word": "impervious", "definition": "not affected by; resistant to", "example": "She seemed impervious to criticism."},
    {"word": "labyrinthine", "definition": "like a labyrinth; complicated", "example": "The building has labyrinthine corridors."},
    {"word": "malevolent", "definition": "having evil intentions", "example": "He gave her a malevolent look."},
    {"word": "nebulous", "definition": "unclear; vague", "example": "His plans remain nebulous."},
    {"word": "obstinate", "definition": "stubbornly refusing to change", "example": "She was obstinate in her refusal."},
    {"word": "pernicious", "definition": "having a harmful effect gradually", "example": "The pernicious effects of pollution."},
]
